#!/bin/bash

echo "🚀 Frontend Railway Deployment Guide"
echo "==================================="
echo ""
echo "Step 1: Login to Railway (if not already logged in)"
echo "Run: railway login"
echo ""
echo "Step 2: Link to your Railway project"
echo "Run: railway link"
echo "Select your existing project or create a new one"
echo ""
echo "Step 3: Create a new service for frontend"
echo "Since you already have a backend service, you'll need to add a new service:"
echo "Run: railway service create frontend"
echo ""
echo "Step 4: Deploy the frontend"
echo "Run: railway up"
echo ""
echo "Step 5: Set environment variables in Railway dashboard"
echo "Go to your Railway project dashboard and add these variables to the frontend service:"
echo ""
echo "NEXT_PUBLIC_API_URL=https://valiant-nature-production.up.railway.app"
echo "NEXTAUTH_URL=https://YOUR-FRONTEND-URL.railway.app"
echo "NEXTAUTH_SECRET=your-secure-secret-here"
echo ""
echo "Optional OAuth variables:"
echo "GOOGLE_CLIENT_ID=your-google-client-id"
echo "GOOGLE_CLIENT_SECRET=your-google-client-secret"
echo "GITHUB_CLIENT_ID=your-github-client-id"
echo "GITHUB_CLIENT_SECRET=your-github-client-secret"
echo ""
echo "Step 6: Add custom domain (optional)"
echo "In Railway dashboard, go to Settings > Domains"
echo ""
echo "Note: The frontend URL will be generated after deployment"
echo "You'll need to update NEXTAUTH_URL with the actual frontend URL"