#!/bin/bash

echo "GitHub Push Helper"
echo "=================="
echo ""
echo "To push your changes to GitHub, you need to:"
echo ""
echo "1. Create a Personal Access Token (PAT) on GitHub:"
echo "   - Go to: https://github.com/settings/tokens/new"
echo "   - Give it a name (e.g., 'SAYU-project')"
echo "   - Select scopes: 'repo' (full control of private repositories)"
echo "   - Click 'Generate token'"
echo "   - COPY THE TOKEN NOW (you won't see it again!)"
echo ""
echo "2. Run this command (replace with your info):"
echo ""
echo "git push https://YOUR_GITHUB_USERNAME:YOUR_TOKEN@github.com/commet/SAYU.git main"
echo ""
echo "Example:"
echo "git push https://commet:ghp_xxxxxxxxxxxx@github.com/commet/SAYU.git main"
echo ""
echo "Note: The token will look like: ghp_xxxxxxxxxxxx"