-- SAYU Masters Collection Integration (FIXED)
-- 13개 최적화된 Masters 작품 추가 - year 컬럼 제거
-- 생성일: 2025-08-21T19:23:21.197Z

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'portrait-after-a-costume-ball-portrait-of-madame-dietz-monnin',
  'Portrait After A Costume Ball Portrait Of Madame Dietz Monnin',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/portrait-after-a-costume-ball-portrait-of-madame-dietz-monnin.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/portrait-after-a-costume-ball-portrait-of-madame-dietz-monnin.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/portrait-after-a-costume-ball-portrait-of-madame-dietz-monnin.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'INFP',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'roses-5',
  'Roses 5',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/roses-5.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/roses-5.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/roses-5.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ISFP',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'charing-cross-bridge',
  'Charing Cross Bridge',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/charing-cross-bridge.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/charing-cross-bridge.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/charing-cross-bridge.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'INFJ',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'on-the-stage',
  'On The Stage',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/on-the-stage.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/on-the-stage.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/on-the-stage.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ISFJ',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'grapes-lemons-pears-and-apples',
  'Grapes Lemons Pears And Apples',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/grapes-lemons-pears-and-apples.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/grapes-lemons-pears-and-apples.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/grapes-lemons-pears-and-apples.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ENFP',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'wheat-field-with-cypresses',
  'Wheat Field With Cypresses',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/wheat-field-with-cypresses.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/wheat-field-with-cypresses.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/wheat-field-with-cypresses.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ESFP',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'mademoiselle-malo',
  'Mademoiselle Malo',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/mademoiselle-malo.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/mademoiselle-malo.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/mademoiselle-malo.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ENFJ',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'madame-rene-de-gas',
  'Madame Rene De Gas',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/madame-rene-de-gas.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/madame-rene-de-gas.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/madame-rene-de-gas.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ESFJ',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'vineyards-at-auvers',
  'Vineyards At Auvers',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/vineyards-at-auvers.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/vineyards-at-auvers.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/vineyards-at-auvers.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'INFP',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'madame-camus',
  'Madame Camus',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/madame-camus.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/madame-camus.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/madame-camus.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ISFP',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'the-terrace-at-saint-germain-spring',
  'The Terrace At Saint Germain Spring',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/the-terrace-at-saint-germain-spring.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/the-terrace-at-saint-germain-spring.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/the-terrace-at-saint-germain-spring.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'INFJ',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'harlequin',
  'Harlequin',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/harlequin.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/harlequin.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/harlequin.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ISFJ',
  'Masters'
);

INSERT INTO artworks (
  id, 
  title, 
  artist, 
  medium, 
  dimensions, 
  description, 
  image_url, 
  thumbnail_url, 
  source, 
  source_url, 
  tags, 
  color_palette, 
  style_period, 
  genre, 
  location, 
  created_at, 
  updated_at,
  sayu_type,
  category
) VALUES (
  'girl-in-red',
  'Girl In Red',
  'Masters Collection',
  'Oil on Canvas',
  'Various',
  'Masterpiece from the Artvee Masters Collection featuring classical artistic techniques and themes.',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/girl-in-red.jpg',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/w_1200,q_80,f_auto/v1753790141/sayu/artvee/masters/sayu/artvee/masters/girl-in-red.jpg',
  'Artvee Masters',
  'https://res.cloudinary.com/dkdzgpj3n/image/upload/v1753790141/sayu/artvee/masters/sayu/artvee/masters/girl-in-red.jpg',
  ARRAY['masters', 'classical', 'fine-art', 'painting'],
  ARRAY['classical', 'warm-tones', 'traditional'],
  'Classical',
  'Classical Art',
  'Masters Collection',
  NOW(),
  NOW(),
  'ENFP',
  'Masters'
);

-- Masters 카테고리 확인 쿼리
SELECT category, COUNT(*) as count 
FROM artworks 
WHERE category = 'Masters'
GROUP BY category;

-- 성공 확인 쿼리  
SELECT id, title, artist, category, sayu_type
FROM artworks 
WHERE category = 'Masters'
ORDER BY created_at DESC;