CREATE TABLE IF NOT EXISTS venues (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  city VARCHAR(100),
  district VARCHAR(100),
  country VARCHAR(2) DEFAULT 'KR'::character varying,
  type VARCHAR(50) DEFAULT 'gallery'::character varying,
  tier INTEGER DEFAULT 2,
  website VARCHAR(500),
  address VARCHAR(500),
  instagram VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  latitude DECIMAL,
  longitude DECIMAL,
  phone VARCHAR(50),
  rating DECIMAL,
  review_count INTEGER DEFAULT 0,
  opening_hours JSONB,
  admission_fee JSONB,
  google_place_id VARCHAR(200),
  data_completeness INTEGER DEFAULT 0,
  last_updated TIMESTAMPTZ DEFAULT NOW()
);