CREATE TABLE IF NOT EXISTS global_venues (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_local VARCHAR(255),
  description TEXT,
  description_local TEXT,
  country VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  address TEXT,
  address_local TEXT,
  latitude DECIMAL,
  longitude DECIMAL,
  phone VARCHAR(50),
  email VARCHAR(255),
  website VARCHAR(500),
  social_media JSONB,
  venue_type VARCHAR(50) NOT NULL,
  venue_category VARCHAR(50),
  art_focus VARCHAR(100),
  opening_hours JSONB,
  admission_info JSONB,
  accessibility_info TEXT,
  languages_supported TEXT[],
  google_place_id VARCHAR(255),
  foursquare_venue_id VARCHAR(255),
  tripadvisor_id VARCHAR(255),
  facebook_page_id VARCHAR(255),
  data_source VARCHAR(50) NOT NULL,
  data_quality_score INTEGER DEFAULT 0,
  verification_status VARCHAR(20) DEFAULT 'unverified'::character varying,
  last_verified TIMESTAMPTZ,
  personality_matches TEXT[] DEFAULT '{}'::integer[],
  emotion_signatures JSONB,
  recommendation_priority INTEGER DEFAULT 50,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by VARCHAR(50) DEFAULT 'system'::character varying,
  name_en VARCHAR(255),
  district VARCHAR(100),
  tier INTEGER,
  is_active BOOLEAN DEFAULT true,
  rating DECIMAL,
  review_count INTEGER,
  data_completeness INTEGER,
  admission_fee JSONB,
  province VARCHAR(100),
  city_en VARCHAR(100),
  name_ko VARCHAR(255),
  city_ko VARCHAR(100),
  address_ko TEXT,
  description_ko TEXT,
  admission_info_ko TEXT,
  address_en TEXT,
  admission_info_en TEXT
);