CREATE TABLE IF NOT EXISTS artists (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_ko VARCHAR(255),
  birth_year INTEGER,
  death_year INTEGER,
  nationality VARCHAR(100),
  nationality_ko VARCHAR(100),
  bio TEXT,
  bio_ko TEXT,
  copyright_status VARCHAR(50) DEFAULT 'unknown'::character varying,
  follow_count INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  era VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  images JSONB DEFAULT '{}'::jsonb,
  sources JSONB DEFAULT '{}'::jsonb,
  license_info JSONB DEFAULT '{}'::jsonb,
  official_links JSONB DEFAULT '{}'::jsonb,
  representation JSONB DEFAULT '{}'::jsonb,
  recent_exhibitions JSONB DEFAULT '[]'::jsonb,
  media_links JSONB DEFAULT '{}'::jsonb,
  is_verified BOOLEAN DEFAULT false,
  verification_date TIMESTAMPTZ,
  verification_method VARCHAR(50),
  artist_managed JSONB DEFAULT '{}'::jsonb,
  permissions JSONB DEFAULT '{}'::jsonb,
  purchase_links JSONB DEFAULT '{}'::jsonb,
  apt_profile JSONB,
  importance_score INTEGER DEFAULT 30,
  importance_tier INTEGER DEFAULT 4,
  updated_by_system BOOLEAN DEFAULT false,
  popularity_score INTEGER DEFAULT 0,
  educational_value INTEGER DEFAULT 0,
  market_influence INTEGER DEFAULT 0,
  external_data JSONB DEFAULT '{}'::jsonb
);