CREATE TABLE IF NOT EXISTS exhibitions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  institution_id UUID,
  title_en VARCHAR(500) NOT NULL,
  title_local VARCHAR(500),
  subtitle VARCHAR(500),
  start_date date NOT NULL,
  end_date date NOT NULL,
  status VARCHAR(50) DEFAULT 'upcoming'::character varying,
  description TEXT,
  curator VARCHAR(200),
  artists TEXT[],
  artworks_count INTEGER,
  ticket_price JSONB,
  official_url VARCHAR(500),
  press_release_url VARCHAR(500),
  virtual_tour_url VARCHAR(500),
  exhibition_type VARCHAR(100) DEFAULT 'temporary'::character varying,
  genres TEXT[],
  tags TEXT[],
  view_count INTEGER DEFAULT 0,
  created_at timestamp with time zone DEFAULT NOW(),
  updated_at timestamp with time zone DEFAULT NOW(),
  venue_id INTEGER,
  venue_name VARCHAR(255),
  venue_city VARCHAR(100),
  venue_country VARCHAR(2) DEFAULT 'KR'::character varying,
  source VARCHAR(100) DEFAULT 'manual'::character varying,
  source_url VARCHAR(500),
  contact_info VARCHAR(200),
  collected_at TIMESTAMPTZ,
  submission_id INTEGER,
  ai_verified BOOLEAN DEFAULT false,
  ai_confidence DECIMAL DEFAULT 0.0,
  website_url TEXT,
  venue_address TEXT,
  phone_number VARCHAR(50),
  admission_fee TEXT,
  operating_hours TEXT
);