CREATE TABLE IF NOT EXISTS global_exhibitions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  venue_id INTEGER,
  title VARCHAR(255) NOT NULL,
  title_local VARCHAR(255),
  subtitle TEXT,
  description TEXT,
  description_local TEXT,
  artists JSONB,
  curator VARCHAR(255),
  curator_local VARCHAR(255),
  start_date date NOT NULL,
  end_date date NOT NULL,
  opening_reception TIMESTAMPTZ,
  ticket_required BOOLEAN DEFAULT false,
  ticket_price JSONB,
  booking_url VARCHAR(500),
  booking_required BOOLEAN DEFAULT false,
  exhibition_type VARCHAR(50),
  art_medium VARCHAR(100),
  themes TEXT[],
  featured_artworks JSONB,
  official_url VARCHAR(500),
  catalog_url VARCHAR(500),
  press_kit_url VARCHAR(500),
  virtual_tour_url VARCHAR(500),
  poster_image_url VARCHAR(500),
  gallery_images JSONB,
  promotional_video_url VARCHAR(500),
  data_source VARCHAR(50) NOT NULL,
  data_quality_score INTEGER DEFAULT 0,
  external_exhibition_id VARCHAR(255),
  personality_matches TEXT[] DEFAULT '{}'::integer[],
  emotion_signatures JSONB,
  ai_generated_description TEXT,
  recommendation_score INTEGER DEFAULT 50,
  status VARCHAR(20) DEFAULT 'active'::character varying,
  visibility VARCHAR(20) DEFAULT 'public'::character varying,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);