CREATE TABLE IF NOT EXISTS global_data_quality_metrics (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  metric_date date DEFAULT CURRENT_DATE,
  total_venues INTEGER DEFAULT 0,
  verified_venues INTEGER DEFAULT 0,
  venues_with_coordinates INTEGER DEFAULT 0,
  venues_with_contact_info INTEGER DEFAULT 0,
  venues_with_opening_hours INTEGER DEFAULT 0,
  venues_with_social_media INTEGER DEFAULT 0,
  average_venue_quality_score DECIMAL,
  total_exhibitions INTEGER DEFAULT 0,
  active_exhibitions INTEGER DEFAULT 0,
  exhibitions_with_images INTEGER DEFAULT 0,
  exhibitions_with_booking_info INTEGER DEFAULT 0,
  average_exhibition_quality_score DECIMAL,
  google_places_venues INTEGER DEFAULT 0,
  foursquare_venues INTEGER DEFAULT 0,
  web_scraped_venues INTEGER DEFAULT 0,
  manual_venues INTEGER DEFAULT 0,
  countries_covered INTEGER DEFAULT 0,
  cities_covered INTEGER DEFAULT 0,
  daily_venues_collected INTEGER DEFAULT 0,
  daily_exhibitions_collected INTEGER DEFAULT 0,
  collection_success_rate DECIMAL,
  average_collection_duration_minutes DECIMAL,
  duplicate_detection_rate DECIMAL,
  api_error_rate DECIMAL,
  data_freshness_days DECIMAL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);